DROP DATABASE IF EXISTS DayPlannerEvents;
CREATE DATABASE DayPlannerEvents;
USE DayPlannerEvents;

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE ,
password VARCHAR(255) NOT NULL
);

CREATE TABLE events(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
startTime TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP ,
endTime TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
MOTD BOOLEAN DEFAULT FALSE,
description TEXT NOT NULL,
user_id INT NOT NULL,
CONSTRAINT FOREIGN KEY(user_id) REFERENCES users(id) ,
UNIQUE(startTime,endTime,user_id)
);

